version: '3.8'

services:
  container1:
    image: mysql:8.0
    container_name: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: 123qwe
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    volumes:
      - ./data/container1:/var/lib/mysql
    networks:
      - mysql_net
    command:
      --server-id=1
      --log-bin=mysql-bin
      --binlog-do-db=testdb
      --default-authentication-plugin=mysql_native_password

  container2:
    image: mysql:8.0
    container_name: mysql_client
    environment:
      MYSQL_ROOT_PASSWORD: 123qwe
    ports:
      - "3307:3306"
    volumes:
      - ./data/container2:/var/lib/mysql
    networks:
      - mysql_net
    command:
      --server-id=2
      --relay-log=mysql-relay
      --log-bin=mysql-bin
      --read-only=1
      --default-authentication-plugin=mysql_native_password

networks:
  mysql_net:
    driver: bridge

